Controllers/CategoryController.cs
using Event.Application.Features.Category.Commands.CreateCategory;
using Event.Application.Features.Category.Commands.DeleteCategory;
using Event.Application.Features.Category.Commands.UpdateCategory;
using Event.Application.Features.Category.Queries.GetCategoryDetails;
using Event.Application.Features.Category.Queries.GetCategoryList;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Event.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IMediator _mediator;

        public CategoryController(IMediator mediator)
        {
            _mediator = mediator;
        }


        [HttpGet]
        public async Task<ActionResult<List<GetCategoryListViewModel>>> GetListCategories(Guid Id)
        {
            ViewBag.EventId = Id;
            return View(await _mediator.Send(new GetCategoryListQuery() { EventId = Id }));
        }

        [HttpGet]
        public async Task<ActionResult<GetCatgoryDetailsViewModel>> GetCategoryById(Guid Id)
        {
            return View(await _mediator.Send(new GetCategoryDetailsQuery() { CategoryId = Id }));
        }


        [HttpGet]
        public IActionResult CreateCategory(Guid EventId)
        {
            ViewBag.EventId = EventId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory([FromForm] CreateCategoryCommand createCategoryCommand)
        {
            Guid id = await _mediator.Send(createCategoryCommand);

            return RedirectToAction(nameof(GetListCategories), new { id = createCategoryCommand.EventId });
        }

   
        [HttpGet]
        public async Task<ActionResult<GetCatgoryDetailsViewModel>> UpdateCategory(Guid Id)
        {

            return View(await _mediator.Send(new GetCategoryDetailsQuery() { CategoryId = Id }));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateCategory([FromForm] UpdateCategoryCommand updateCategoryCommand)
        {

            await _mediator.Send(updateCategoryCommand);

            return RedirectToAction(nameof(GetListCategories), new { Id = updateCategoryCommand.EventId });
        }


        [HttpPost]
        public async Task<ActionResult> DeleteCategory(Guid id)
        {
            await _mediator.Send(new DeleteCategoryCommand() { CategoryId = id });

            return Ok(new { key = 1 });
        }
    }
}

Views/Category/CreateCategory.cshtml
@model Event.Application.Features.Category.Commands.CreateCategory.CreateCategoryCommand

@{
    ViewData["Title"] = "Create";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">اضافة قسم</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="CreateCategory" asp-controller="Category">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 <div>
                    <input hidden  asp-for="EventId" value="@ViewBag.EventId" class="form-control" />
                </div>                <div class="form-group">
                    <label asp-for="Name" class="control-label">الاسم بالعربية</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">الاسم بالانجليزية</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListCategories" asp-route-id="@ViewBag.EventId" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Category/GetListCategories.cshtml
@model IEnumerable<Event.Application.Features.Category.Queries.GetCategoryList.GetCategoryListViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-box">

    <h2 class="header-title m-t-0 m-b-30">الاقسام</h2>

    <div>
        <p>
            @Html.ActionLink("اضافة قسم", "CreateCategory", "Category", new {EventId = ViewBag.EventId }, new { @class = "btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" })
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th> الاسم </th>
                    <th> الوصف </th>
                    <th>تعديل</th>
                    <th>حذف</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>

                         <td>
                            <a href="/Category/UpdateCategory/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">تعديل</a>
                        </td>
                        <td>
                            <input type="button" value="&#xf014;"  class="icon-font btn btn-danger btn-rounded" onclick="Delete('@item.Id')"  />
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- -------------------------------------------------------------------------------------------------- -->
    </div><!-- end row -->
</div>
@*
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="jquery-3.6.0.min.js"></script>*@

@section scripts
{
<script>

    function Delete(id) {
         Swal.fire({
             title: 'هل انت متاكد من حذف هذا العنصر  ؟',
             type: 'warning',
             showCancelButton: true,
             confirmButtonColor: '#d33',
             cancelButtonColor: '#3085d6',
             cancelButtonText: 'اغلاق',
             confirmButtonText: 'حذف',
         }).then((result) => {
             if (result.value) {
                 $.ajax({
                     url: "/Category/DeleteCategory",
                     type: "POST",
                     dataType: "json",
                     data: {
                         id: id
                     }, success: function (result) {
                         if (result.data == true) {
                             toastr.success("تم الحذف بنجاح");
                             setTimeout(function () {
                             }, 3000);
                         }
                         window.location.reload();
                     },
                     failure: function (info) {

                     }
                 })
             }
         })
     }

</script>
}

Views/Category/UpdateCategory.cshtml
@model Event.Application.Features.Category.Queries.GetCategoryDetails.GetCatgoryDetailsViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">تعديل</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="UpdateCategory" asp-controller="Category">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="EventId" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label">الاسم</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">الوصف</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                
                
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListCategories"  asp-route-id="@Model.EventId" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}