Controllers/AlbumController.cs
using Event.Application.Features.Album.Commands.CreateAlbum;
using Event.Application.Features.Album.Commands.DeleteAlbum;
using Event.Application.Features.Album.Commands.UpdateAlbum;
using Event.Application.Features.Album.Queries.GetAlbumDetails;
using Event.Application.Features.Album.Queries.GetAlbumList;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Event.Web.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IMediator _mediator;

        public AlbumController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public async Task<ActionResult<List<GetAlbumListViewModel>>> GetListAlbums(Guid Id)
        {
            ViewBag.EventId = Id;
            return View(await _mediator.Send(new GetAlbumListQuery() { EventId = Id }));
        }

        [HttpGet]
        public async Task<ActionResult<GetAlbumDetailsViewModel>> GetCategoryById(Guid Id)
        {
            return View(await _mediator.Send(new GetAlbumDetailsQuery() { AlbumId = Id }));
        }

        [HttpGet]
        public IActionResult CreateAlbum(Guid EventId)
        {
            ViewBag.EventId = EventId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAlbum([FromForm] CreateAlbumCommand createAlbumCommand)
        {
            Guid id = await _mediator.Send(createAlbumCommand);

            return RedirectToAction(nameof(GetListAlbums), new { id = createAlbumCommand.EventId });
        }

        [HttpGet]
        public async Task<ActionResult<GetAlbumDetailsViewModel>> UpdateAlbum(Guid Id)
        {
            return View(await _mediator.Send(new GetAlbumDetailsQuery() { AlbumId = Id }));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateAlbum([FromForm] UpdateAlbumCommand updateAlbumCommand)
        {

            await _mediator.Send(updateAlbumCommand);

            return RedirectToAction(nameof(GetListAlbums), new {Id = updateAlbumCommand.EventId});
        }


        [HttpPost]
        public async Task<ActionResult> DeleteAlbum(Guid id)
        {
            await _mediator.Send(new DeleteAlbumCommand() { AlbumId = id });

            return Ok(new { key = 1 });
        }
    }
}

Views/Album/CreateAlbum.cshtml
@model Event.Application.Features.Album.Commands.CreateAlbum.CreateAlbumCommand
@{
    ViewData["Title"] = "Create";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">اضافة البوم</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="CreateAlbum" asp-controller="Album">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div>
                    <input hidden asp-for="EventId" value="@ViewBag.EventId" class="form-control" />
                </div>   
                <div class="form-group">
                    <label asp-for="Title" class="control-label">العنوان</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListAlbums" asp-route-id="@ViewBag.EventId" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Album/GetListAlbums.cshtml
@model IEnumerable<Event.Application.Features.Album.Queries.GetAlbumList.GetAlbumListViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-box">

    <h2 class="header-title m-t-0 m-b-30">الالبومات</h2>

    <div>
        <p>
            @Html.ActionLink("اضافة البوم", "CreateAlbum", "Album", new {EventId = ViewBag.EventId }, new { @class = "btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" })
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th> العنوان </th>
                    <th>تعديل</th>
                    <th>حذف</th>
                    <th>الصور</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>

                         <td>
                            <a href="/Album/UpdateAlbum/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">تعديل</a>
                        </td>
                        <td>
                            <input type="button" value="&#xf014;"  class="icon-font btn btn-danger btn-rounded" onclick="Delete('@item.Id')"  />
                        </td>
                         <td>
                            <a href="/Images/GetListImages/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">عرض</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- -------------------------------------------------------------------------------------------------- -->
    </div><!-- end row -->
</div>
@*
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="jquery-3.6.0.min.js"></script>*@

@section scripts
{
<script>

    function Delete(id) {
         Swal.fire({
             title: 'هل انت متاكد من حذف هذا العنصر  ؟',
             type: 'warning',
             showCancelButton: true,
             confirmButtonColor: '#d33',
             cancelButtonColor: '#3085d6',
             cancelButtonText: 'اغلاق',
             confirmButtonText: 'حذف',
         }).then((result) => {
             if (result.value) {
                 $.ajax({
                     url: "/Album/DeleteAlbum",
                     type: "POST",
                     dataType: "json",
                     data: {
                         id: id
                     }, success: function (result) {
                         if (result.data == true) {
                             toastr.success("تم الحذف بنجاح");
                             setTimeout(function () {
                             }, 3000);
                         }
                         window.location.reload();
                     },
                     failure: function (info) {

                     }
                 })
             }
         })
     }

</script>
}

Views/Album/UpdateAlbum.cshtml
@model Event.Application.Features.Album.Queries.GetAlbumDetails.GetAlbumDetailsViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">تعديل</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="UpdateAlbum" asp-controller="Album">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="EventId" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label">الاسم</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListAlbums"  asp-route-id="@Model.EventId" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}