Controllers/SourceController.cs
using Event.Application.Features.Event.Queries.GetPostsList;
using Event.Application.Features.Source.Commands.CreateSource;
using Event.Application.Features.Source.Commands.DeleteSource;
using Event.Application.Features.Source.Commands.UpdateSource;
using Event.Application.Features.Source.Queries.GetSourceDetails;
using Event.Application.Features.Source.Queries.GetSourceList;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Event.Web.Controllers
{
    public class SourceController : Controller
    {
        private readonly IMediator _mediator;

        public SourceController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public async Task<ActionResult<List<GetSourceListViewModel>>> GetListSources()
        {
            return View(await _mediator.Send(new GetSourceListQuery()));
        }

        [HttpGet]
        public async Task<ActionResult<GetSourceDetailsViewModel>> GetEventById(Guid Id)
        {
            return View(await _mediator.Send(new GetSourceDetailsQuery() { SourceId = Id }));
        }

        [HttpGet]
        public async Task<ActionResult> CreateSource()
        {
           var data = await _mediator.Send(new GetEventListQuery());

            ViewBag.Event = data.Select(c => new EventSelectedViewModel
            {
                    EventId = c.Id,
                    Name = c.NameAr
                });
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSource([FromForm] CreateSourceCommand createSourceCommand)
        {
            Guid id = await _mediator.Send(createSourceCommand);

            return RedirectToAction(nameof(GetListSources));
        }

        [HttpGet]
        public async Task<ActionResult<GetSourceDetailsViewModel>> UpdateSource(Guid Id)
        {
            return View(await _mediator.Send(new GetSourceDetailsQuery() { SourceId = Id }));
        }
        [HttpPost]
        public async Task<ActionResult> UpdateSource([FromForm] UpdateSourceCommand updateEventCommand)
        {
            await _mediator.Send(updateEventCommand);

            return RedirectToAction(nameof(GetListSources));
        }

        [HttpPost]
        public async Task<ActionResult> DeleteSource(Guid id)
        {
            await _mediator.Send(new DeleteSourceCommand() { SourceId = id });

            return Ok(new { key = 1 });
        }
    }
}

Views/Source/CreateSource.cshtml
@model Event.Application.Features.Source.Commands.CreateSource.CreateSourceCommand

@{
    ViewData["Title"] = "Create";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">اضافة مصدر</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="CreateSource" asp-controller="Source">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="EventId" class="control-label">اسم الحدث</label>
                    <select id="EventId" class="form-control" asp-for="EventId" 
                            asp-items="@(new SelectList(ViewBag.Event, "EventId", "Name"))">
                        <option value="">اختر الحدث</option>
                    </select>
                    <span asp-validation-for="EventId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">الاسم</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">الوصف</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListSources" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Source/GetListSources.cshtml
@model IEnumerable<Event.Application.Features.Source.Queries.GetSourceList.GetSourceListViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-box">

    <h2 class="header-title m-t-0 m-b-30">المصادر</h2>

    <div>
        <p>
            @Html.ActionLink("اضافة مصدر", "CreateSource", "Source", null, new { @class = "btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" })
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>اسم المصدر</th>
                    <th> الوصف </th>
                    <th>تعديل </th>
                    <th>حذف</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            <a href="/Source/UpdateSource/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">تعديل</a>
                        </td>
                        <td>
                            <input type="button" value="&#xf014;" class="icon-font btn btn-danger btn-rounded" onclick="Delete('@item.Id')" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- -------------------------------------------------------------------------------------------------- -->
    </div><!-- end row -->
</div>
@*
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="jquery-3.6.0.min.js"></script>*@

@section scripts
{
<script>

    function Delete(id) {
         Swal.fire({
             title: 'هل انت متاكد من حذف هذا العنصر  ؟',
             type: 'warning',
             showCancelButton: true,
             confirmButtonColor: '#d33',
             cancelButtonColor: '#3085d6',
             cancelButtonText: 'اغلاق',
             confirmButtonText: 'حذف',
         }).then((result) => {
             if (result.value) {
                 $.ajax({
                     url: "/Source/DeleteSource",
                     type: "POST",
                     dataType: "json",
                     data: {
                         id: id
                     }, success: function (result) {
                         if (result.data == true) {
                             toastr.success("تم الحذف بنجاح");
                             setTimeout(function () {
                             }, 3000);
                         }
                         window.location.reload();
                     },
                     failure: function (info) {

                     }
                 })
             }
         })
     }

</script>
}

Views/Source/UpdateSource.cshtml
@model Event.Application.Features.Source.Queries.GetSourceDetails.GetSourceDetailsViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">تعديل</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="UpdateSource" asp-controller="Source">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="EventId" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label">الاسم</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">الوصف</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListSources" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}