Controllers/EventController.cs
using Event.Application.Features.Event.Commands.CreateEvent;
using Event.Application.Features.Event.Commands.DeleteEvent;
using Event.Application.Features.Event.Commands.UpdateEvent;
using Event.Application.Features.Event.Queries.GetEventDetails;
using Event.Application.Features.Event.Queries.GetEventList;
using Event.Application.Features.Event.Queries.GetPostDetails;
using Event.Application.Features.Event.Queries.GetPostsList;
using Event.Domain.Entities;
using EventTask.Web.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Event.Web.Controllers
{

    public class EventController : Controller
    {
        private readonly IMediator _mediator;

        public EventController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public async Task<ActionResult<List<GetEventListViewModel>>> GetListEvents()
        {
            return View(await _mediator.Send(new GetEventListQuery()));
        }

        [HttpGet]
        public async Task<ActionResult<GetEventDetailsViewModel>> GetEventById(Guid Id)
        {
            return View(await _mediator.Send(new GetEventDetailsQuery() { EventId = Id}));
        }

        [HttpGet]
        public ActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateEvent([FromForm] CreateEventCommand createEventCommand)
        {
            Guid id = await _mediator.Send(createEventCommand);

            return RedirectToAction(nameof(GetListEvents));
        }

        [HttpPost]
        public async Task<ActionResult> DeleteEvent(Guid id)
        {
            await _mediator.Send(new DeleteEventCommand() { EventId = id });

            return Ok(new { key = 1 });
        }

        [HttpGet]
        public async Task<ActionResult<GetEventDetailsViewModel>> UpdateEvent(Guid Id)
        {
            return View(await _mediator.Send(new GetEventDetailsQuery() { EventId = Id }));
        }

        [HttpPost]
        public async Task<ActionResult> UpdateEvent([FromForm] UpdateEventCommand updateEventCommand)
        {
            await _mediator.Send(updateEventCommand);

            return RedirectToAction(nameof(GetListEvents));
        }
    }
}

Views/Event/CreateEvent.cshtml
@model Event.Application.Features.Event.Commands.CreateEvent.CreateEventCommand

@{
    ViewData["Title"] = "Create";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">اضافة حدث</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="CreateEvent" asp-controller="Event" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NameAr" class="control-label">الاسم بالعربية</label>
                    <input asp-for="NameAr" class="form-control" />
                    <span asp-validation-for="NameAr" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NameEn" class="control-label">الاسم بالانجليزية</label>
                    <input asp-for="NameEn" class="form-control" />
                    <span asp-validation-for="NameEn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Content" class="control-label">المحتوي</label>
                    <input asp-for="Content" class="form-control" />
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label">العنوان</label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label">بداية الحدث</label>
                    <input type="date" asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label">نهاية الحدث</label>
                    <input type="date" asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
               <div class="form-group">
                    <label asp-for="CoverImg" class="control-label">الصوره</label>
                    <input type="file" asp-for="CoverImg" class="form-control" />
                    <span asp-validation-for="CoverImg" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListEvents" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Event/GetListEvents.cshtml
@model IEnumerable<Event.Application.Features.Event.Queries.GetEventList.GetEventListViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-box">

    <h2 class="header-title m-t-0 m-b-30">الاحداث</h2>

    <div>
        <p>
            @Html.ActionLink("اضافة حدث", "CreateEvent", "Event", null, new { @class = "btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5" })
        </p>
        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th> الاسم بالعربيه </th>
                    <th> الاسم بالانجليزيه </th>
                    <th> المحتوي العنوان </th>
                    <th>بداية الحدث</th>
                    <th>نهاية الحدث</th>
                    <th>الصوره</th>
                    <th>تعديل</th>
                    <th>حذف</th>
                    <th>الاقسام</th>
                    <th>الالبومات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameAr)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameEn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Content)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndDate)
                        </td>
                        <td>
                            <img src="@item.CoverImg" style="height:100px;width:100px;" />
                        </td>
                       <td>
                            <a href="/Event/UpdateEvent/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">تعديل</a>
                        </td>
                        <td>
                            <input type="button" value="&#xf014;" class="icon-font btn btn-danger btn-rounded" onclick="Delete('@item.Id')" />
                        </td>
                        <td>
                            <a href="/Category/GetListCategories/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">عرض</a>
                        </td> 
                        <td>
                            <a href="/Album/GetListAlbums/@item.Id" class="btn btn-info btn-rounded" role="button" aria-pressed="true">عرض</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- -------------------------------------------------------------------------------------------------- -->
    </div><!-- end row -->
</div>
@*
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="jquery-3.6.0.min.js"></script>*@

@section scripts
{
<script>

    function Delete(id) {
         Swal.fire({
             title: 'هل انت متاكد من حذف هذا العنصر  ؟',
             type: 'warning',
             showCancelButton: true,
             confirmButtonColor: '#d33',
             cancelButtonColor: '#3085d6',
             cancelButtonText: 'اغلاق',
             confirmButtonText: 'حذف',
         }).then((result) => {
             if (result.value) {
                 $.ajax({
                     url: "/Event/DeleteEvent",
                     type: "POST",
                     dataType: "json",
                     data: {
                         id: id
                     }, success: function (result) {
                         if (result.data == true) {
                             toastr.success("تم الحذف بنجاح");
                             setTimeout(function () {
                             }, 3000);
                         }
                         window.location.reload();
                     },
                     failure: function (info) {

                     }
                 })
             }
         })
     }

</script>
}

Views/Event/UpdateEvent.cshtml
@model Event.Application.Features.Event.Queries.GetEventDetails.GetEventDetailsViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">تعديل</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="UpdateEvent" asp-controller="Event" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="CoverImg" />
                <div class="form-group">
                    <label asp-for="NameAr" class="control-label">الاسم بالعربية</label>
                    <input asp-for="NameAr" class="form-control" />
                    <span asp-validation-for="NameAr" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NameEn" class="control-label">الاسم بالانجليزية</label>
                    <input asp-for="NameEn" class="form-control" />
                    <span asp-validation-for="NameEn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Content" class="control-label">المحتوي</label>
                    <input asp-for="Content" class="form-control" />
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label">العنوان</label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label">بداية الحدث</label>
                    <input type="date" asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label">نهاية الحدث</label>
                    <input type="date" asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CoverImg" class="control-label">صورة القديمة</label>
                    <div class="col-md-10">
                        <img src="@Event.Application.Common.PathUrl.DashBordUrl.baseUrlHost@Model.CoverImg" style="width:100px; height:100px; " />
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label">صورة جديدة</label>
                    <input asp-for="ImageFile" class="form-control" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn-new-style btn-rounded" />
                </div>

                <div>
                    <a asp-action="GetListEvents" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}